### ISSUE TITLE
Migrate CI from Travis to Github Workflow to increase collaboration

### ISSUE THREAD

**Issue by etc-tiago** [kripod/otion#27]
When a Ci step of Travis fails only the creator of the pipeline can really see what is happening or which command has failed and why it failed.  When migrating to GitHub Workflow this changes because it is possible to see the CI configuration in the Actions tab and correct it as soon as the step fails.

**Comment by etc-tiago** [comment]
Excuse me, I just didn't find the link to view the log, but anyway, I see the migration as valid to keep the development and the CI in the same place

**Comment by kripod** [comment]
Thank you for the idea!

While I tinkered with this idea in the past, it turns out that writing a GitHub workflow is way more cumbersome than a Travis config at this time. When it comes to continuous package deployments for a monorepo, Travis seems to be a convenient choice.

I don’t feel like a CI change would benefit the project’s quality right now. Please reopen this issue if you feel that the CI/CD process could be drastically improved.

**Comment by etc-tiago** [comment]
Since Github Workflows was launched, I have migrated my repositories from gitlab to github exactly by CI.

I believe that the step logs are more organized and easier to see errors than Travis and others, but it is something that would not change the development drastically.
